// #include "math/Angle.hh"
// #include "math/Box.hh"
// #include "math/Filter.hh"
 #include "Helpers.cc"
// #include "math/MathTypes.hh"
// #include "math/Matrix3.hh"
// #include "math/Matrix4.hh"
// #include "math/Plane.hh"
// #include "math/Pose.hh"
// #include "math/Quaternion.hh"
// #include "math/Rand.hh"
// #include "math/RotationSpline.hh"
// #include "math/Spline.hh"
 #include "Vector2d.cc"
// #include "math/Vector2i.hh"
 #include "Vector3.cc"
// #include "math/Vector4.hh"

