geometry_msgs/Point    position
msi_rover/attitude     attitude
geometry_msgs/Twist    twist

---

float32 fl_steer_ang
float32 fr_steer_ang
float32 rl_steer_ang
float32 rr_steer_ang

float32 fl_wheel_pwm
float32 fr_wheel_pwm
float32 ml_wheel_pwm
float32 mr_wheel_pwm
float32 rl_wheel_pwm
float32 rr_wheel_pwm

bool    short_fl_wheel
bool    short_fr_wheel
bool    short_ml_wheel
bool    short_mr_wheel
bool    short_rl_wheel
bool    short_rr_wheel

bool    ok
